version: '2.15.1'
name: car-monitoring-app
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432 # map port 5433 as external port in order to use pgadmin and inspect the database from outside
    environment:
      - POSTGRES_PASSWORD=omar1128
      - POSTGRES_DB=carmonitor
    networks:
      - shared-network
    volumes:
      - /postgres-data:/var/lib/postgresql/data
  backend:
    container_name: backend-server
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=omar1128
      - DB_PORT=5432
      - DB_NAME=carmonitor
    networks:
      - shared-network
    depends_on:
      - postgres
  frontend:
    container_name: frontend-client
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - REACT_APP_MAPS_API_KEY=AIzaSyCiBdTxx2OkpFb3-nEqicLTdlK8Ssfgl9Y
      - REACT_APP_SERVER_API_URL=http://localhost:5000
    networks:
      - shared-network
    depends_on:
      - backend
networks:
  shared-network:
